name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libxmlrpc-core-c3-dev libglib2.0-dev libfftw3-dev libcfitsio-dev libgsl-dev libcurl4-gnutls-dev swig

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pkgconfig
          
      - name: Build and Install Obit
        run: |
          pip install .
            
      - name: Test Obit import
        run: |
          python -c "from obit import Obit; print(Obit.Version())"
