name: Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test_ubuntu"
  test_ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxmlrpc-core-c3-dev libglib2.0-dev libfftw3-dev libcfitsio-dev libgsl-dev libcurl4-gnutls-dev swig

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pkgconfig pytest
          
      - name: Build and Install Obit
        run: |
          pip install .
            
      - name: Run tests
        run: |
          python -m pytest --verbose tests/
